// Local activities directory — GENERATED from the source CSV, then hand-owned here.
// `prisma/seed.ts` upserts each row by `name` (unique). Category is a key
// (see categories.ts) driving the map marker colour.

export interface ActivitySeed {
  name: string
  category: string
  type?: string
  address?: string
  city?: string
  phone?: string
  notes?: string
  lat?: number
  lng?: number
}

export const ACTIVITIES_SEED: ActivitySeed[] = [
  {
    name: "Achille Restaurant",
    category: "food",
    type: "Restaurante/Pizzería",
    address: "Corso Giuseppe Garibaldi 132",
    city: "Valenza",
    phone: "+39 334 784 7651",
    notes: "Grande, familiar, apertura continua",
    lat: 45.0112207,
    lng: 8.6435329,
  },
  {
    name: "Osteria della Piazzetta da Piero",
    category: "food",
    type: "Osteria",
    address: "Piazza Verdi 5",
    city: "Valenza",
    phone: "+39 0131 953525",
    notes: "Cocina tradicional, céntrica",
    lat: 45.0135266,
    lng: 8.6441856,
  },
  {
    name: "Ristorante Pizzeria Duomo",
    category: "food",
    type: "Pizzería",
    address: "Piazza 31 Martiri 9",
    city: "Valenza",
    phone: "+39 0131 185 0094",
    notes: "Pizza y fassona, junto al Duomo",
    lat: 45.0149489,
    lng: 8.6458559,
  },
  {
    name: "L'Eccellenza di Uku",
    category: "food",
    type: "Restaurante",
    address: "Viale Dante Alighieri 20",
    city: "Valenza",
    phone: "+39 0131 481938",
    notes: "Familiar, ingredientes frescos",
    lat: 45.0120437,
    lng: 8.6417868,
  },
  {
    name: "Trattoria Pizzeria PaneLardo",
    category: "food",
    type: "Trattoria/Pizzería",
    address: "Via Ludovico Ariosto 6",
    city: "Valenza",
    phone: "+39 0131 041646",
    notes: "Pizza fina, buen precio; reservar findes",
    lat: 45.0113889,
    lng: 8.6405556,
  },
  {
    name: "La Canva",
    category: "food",
    type: "Enoteca/Bistró",
    address: "Via Canonico Zuffi 1",
    city: "Valenza",
    phone: "+39 351 497 5872",
    notes: "Mejor puntuada del pueblo; vinos y tabla de fiambres",
    lat: 45.011697,
    lng: 8.644175,
  },
  {
    name: "Cascina Gaia",
    category: "food",
    type: "Agriturismo",
    address: "Strada alla Nuova Fornace",
    city: "Valenza",
    phone: "+39 339 677 3875",
    notes: "Granja educativa + restaurante; vie-dom",
    lat: 45.0251448,
    lng: 8.6217775,
  },
  {
    name: "Le Mout",
    category: "food",
    type: "Sushi",
    address: "Corso Giuseppe Garibaldi 138",
    city: "Valenza",
    phone: "+39 366 306 5513",
    notes: "AYCE pequeño, buen precio",
    lat: 45.0104407,
    lng: 8.6429938,
  },
  {
    name: "Ikka Sushi",
    category: "food",
    type: "Sushi",
    address: "Viale della Repubblica 4/A",
    city: "Valenza",
    phone: "+39 371 447 2614",
    notes: "AYCE grande, pedido por tablet",
    lat: 45.0149238,
    lng: 8.6415693,
  },
  {
    name: "L'Ariosa Restaurant & Drink",
    category: "food",
    type: "Restaurante",
    address: "Strada Astigliano 42",
    city: "Valenza",
    phone: "+39 351 508 9429",
    notes: "En las afueras",
    lat: 44.9936729,
    lng: 8.5986033,
  },
  {
    name: "Caffè Del Centro",
    category: "food",
    type: "Café/Bar",
    address: "Viale Luciano Oliva 2A",
    city: "Valenza",
    phone: "+39 338 350 6077",
    notes: "Desayuno y aperitivo",
    lat: 45.0107217,
    lng: 8.6440682,
  },
  {
    name: "Bar Il Faraone",
    category: "food",
    type: "Café/Aperitivo",
    address: "Via Fratelli Cairoli 5",
    city: "Valenza",
    phone: "+39 0131 185 0027",
    notes: "Aperitivo generoso, abre tarde, terraza",
    lat: 45.0118608,
    lng: 8.6428967,
  },
  {
    name: "La Maison du Café",
    category: "food",
    type: "Café/Panadería",
    address: "Via del Castagnone 4",
    city: "Valenza",
    phone: "+39 329 710 9098",
    notes: "Sándwiches y croissants, abre temprano",
    lat: 45.0111406,
    lng: 8.6381964,
  },
  {
    name: "Dark Fit",
    category: "sport",
    type: "Gimnasio",
    address: "Piazza 31 Martiri 16",
    city: "Valenza",
    phone: "+39 351 842 4549",
    notes: "Abierto 6-24h todos los días",
    lat: 45.0145395,
    lng: 8.6456542,
  },
  {
    name: "Agorà Palestre",
    category: "sport",
    type: "Gimnasio",
    address: "Via Giuseppe Melgara 8",
    city: "Valenza",
    phone: "+39 0131 941574",
    notes: "Máquinas + clases grupales",
    lat: 45.0120452,
    lng: 8.6412296,
  },
  {
    name: "A.S. Ginnastica Valentia",
    category: "sport",
    type: "Gimnasio/Gimnasia",
    address: "Via Michelangelo 3",
    city: "Valenza",
    phone: "+39 0131 951325",
    notes: "Mejor puntuada; clases para todo nivel",
    lat: 45.0116539,
    lng: 8.6358137,
  },
  {
    name: "Spazio24",
    category: "sport",
    type: "Fuerza/Acondicionamiento",
    address: "Via Bologna 36",
    city: "Valenza",
    phone: "+39 345 383 9938",
    notes: "Método por networks",
    lat: 45.0140954,
    lng: 8.6359002,
  },
  {
    name: "Sardu G. Strength & Conditioning",
    category: "sport",
    type: "Entrenador personal",
    address: "Via Bologna 36",
    city: "Valenza",
    phone: "+39 351 609 3537",
    notes: "Entrenamiento atlético personalizado",
    lat: 45.0140812,
    lng: 8.6359188,
  },
  {
    name: "Palazzetto dello Sport",
    category: "sport",
    type: "Polideportivo",
    address: "Via San Giovanni 25",
    city: "Valenza",
    phone: "+39 0131 949244",
    notes: "Básquet/vóley y eventos",
    lat: 45.0145781,
    lng: 8.6405781,
  },
  {
    name: "Stadio Comunale",
    category: "sport",
    type: "Estadio/Fútbol",
    address: "Via Napoli 1",
    city: "Valenza",
    notes: "US Valenza; fútbol",
    lat: 45.0050711,
    lng: 8.6395701,
  },
  {
    name: "Tennis Nuovo Paradiso",
    category: "sport",
    type: "Tenis/Pádel",
    address: "Strada Pontecurone 37",
    city: "Valenza",
    phone: "+39 0131 945322",
    notes: "Canchas de tierra + 2 de pádel",
    lat: 45.0078048,
    lng: 8.6543817,
  },
  {
    name: "A.D.S. Bocciofila Belvedere",
    category: "sport",
    type: "Bochas",
    address: "Via Michelangelo 17",
    city: "Valenza",
    phone: "+39 0131 924091",
    notes: "Club de bochas",
    lat: 45.0111884,
    lng: 8.6356007,
  },
  {
    name: "Judo Ginnic Club",
    category: "martial",
    type: "Judo/TRX",
    address: "Via Michelangelo 3",
    city: "Valenza",
    phone: "+39 0131 033886",
    notes: "Judo histórico + clases de TRX",
    lat: 45.0121292,
    lng: 8.6358439,
  },
  {
    name: "Alliance Self Defense Academy",
    category: "martial",
    type: "Krav Maga",
    address: "Via del Lavoro 4",
    city: "Valenza",
    phone: "+39 338 525 7656",
    notes: "Única escuela con aval israelí directo",
    lat: 45.0211841,
    lng: 8.622513,
  },
  {
    name: "APV Boxe Valenza",
    category: "martial",
    type: "Boxeo",
    address: "Via Raffaello 2",
    city: "Valenza",
    notes: "Entrenamiento tardes",
    lat: 45.0104437,
    lng: 8.6338818,
  },
  {
    name: "MB Studios",
    category: "dance",
    type: "Baile social",
    address: "Via Michelangelo 3/bis",
    city: "Valenza",
    phone: "+39 338 990 5531",
    notes: "Mejor valorado; adultos",
    lat: 45.0115368,
    lng: 8.6357037,
  },
  {
    name: "GMA Dance Academy",
    category: "dance",
    type: "Danza/Fitness",
    address: "Via Cremona",
    city: "Valenza",
    notes: "Adultos y chicos",
    lat: 45.0157489,
    lng: 8.6346472,
  },
  {
    name: "Accademia di Danza Vietata Riproduzione",
    category: "dance",
    type: "Danza",
    address: "Via Bologna 36",
    city: "Valenza",
    phone: "+39 338 542 9398",
    notes: "Lun/mié/vie",
    lat: 45.0140954,
    lng: 8.6359002,
  },
  {
    name: "Scuola di Tango Argentino",
    category: "dance",
    type: "Tango",
    address: "Viale Vicenza 58",
    city: "Valenza",
    phone: "+39 380 298 0682",
    notes: "Ficha sin verificar; solo mié 21:00-22:30; confirmar por tel.",
    lat: 45.014657,
    lng: 8.648785,
  },
  {
    name: "Gaiamusica APS",
    category: "music",
    type: "Escuela música/Coro/Teatro",
    address: "Via Giuseppe Mazzini 15",
    city: "Valenza",
    phone: "+39 351 489 9312",
    notes: "Coro, canto, piano, teatro, musical",
    lat: 45.0122355,
    lng: 8.6448142,
  },
  {
    name: "Associazione Amici della Musica",
    category: "music",
    type: "Escuela de música",
    address: "Via Giosuè Carducci 4a",
    city: "Valenza",
    phone: "+39 338 659 4152",
    notes: "Piano, guitarra, batería, violín, canto",
    lat: 45.0150639,
    lng: 8.6432931,
  },
  {
    name: "For.Al «V. Melchiorre» (scuola orafa)",
    category: "goldsmith",
    type: "Curso de orfebrería",
    address: "Valenza",
    city: "Valenza",
    notes: "Formación orafa; dirección exacta a confirmar",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "M.G. Gold - La Fabbrica del Gioiello",
    category: "goldsmith",
    type: "Taller de joyería",
    address: "Via Pellizzari 29",
    city: "Valenza",
    phone: "+39 333 949 2192",
    notes: "Crear/encargar pieza con maestro",
    lat: 45.0143799,
    lng: 8.6486029,
  },
  {
    name: "Duomo di Santa Maria Maggiore",
    category: "culture",
    type: "Iglesia/Catedral",
    address: "Piazza 31 Martiri 3",
    city: "Valenza",
    notes: "Barroca 400+ años, órgano Serassi",
    lat: 45.0146598,
    lng: 8.6462616,
  },
  {
    name: "Teatro Sociale",
    category: "culture",
    type: "Teatro",
    address: "Corso Giuseppe Garibaldi 58",
    city: "Valenza",
    phone: "+39 0131 920154",
    notes: "Teatro neoclásico de 1861",
    lat: 45.0131468,
    lng: 8.6445552,
  },
  {
    name: "Cinema di Valenza",
    category: "culture",
    type: "Cine",
    address: "Corso Giuseppe Garibaldi 58",
    city: "Valenza",
    phone: "+39 324 083 8829",
    notes: "Sala íntima (mismo complejo del teatro)",
    lat: 45.0131468,
    lng: 8.6445552,
  },
  {
    name: "MOD - Museo Oreficeria Diffuso / Centro Espositivo Arte Orafa",
    category: "culture",
    type: "Museo orfebrería",
    address: "Complesso San Domenico, Via IX Febbraio",
    city: "Valenza",
    notes: "Taller orafo reconstruido + gemología (inaug. 2024)",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Villa Scalcabarozzi",
    category: "culture",
    type: "Sala de exposiciones",
    address: "Via Giuseppe Mazzini 49",
    city: "Valenza",
    notes: "Villa liberty; muestras temporales de joyería",
    lat: 45.011898,
    lng: 8.645514,
  },
  {
    name: "Palazzo Pellizzari",
    category: "culture",
    type: "Palacio/Municipio",
    address: "Via Pellizzari 2",
    city: "Valenza",
    notes: "Neoclásico 1834; escalinata, frescos",
    lat: 45.014498,
    lng: 8.646307,
  },
  {
    name: "Palazzo Valentino - Centro Comunale di Cultura",
    category: "culture",
    type: "Biblioteca/Cultura",
    address: "Piazza XXXI Martiri",
    city: "Valenza",
    notes: "Centro cultural y biblioteca",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Oratorio di San Bartolomeo",
    category: "culture",
    type: "Oratorio",
    address: "Valenza (centro storico)",
    city: "Valenza",
    notes: "En el circuito del casco antiguo",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Villa del Pero",
    category: "culture",
    type: "Villa histórica",
    address: "Valenza (afueras)",
    city: "Valenza",
    notes: "Arquitectura del s. XVIII",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Riserva Naturale Garzaia di Valenza",
    category: "outdoors",
    type: "Reserva natural",
    address: "Norte del centro, sobre el Po",
    city: "Valenza",
    notes: "Reserva integral; birdwatching de garzas",
    lat: 45.0549911,
    lng: 8.6430642,
  },
  {
    name: "Argini del Po",
    category: "outdoors",
    type: "Río/Ciclismo/Running",
    address: "Borde del Po",
    city: "Valenza",
    notes: "Correr/bici por los terraplenes del Po",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Giardini Pubblici Viale Oliva",
    category: "outdoors",
    type: "Parque",
    address: "Viale Luciano Oliva",
    city: "Valenza",
    notes: "Parque céntrico con juegos",
    lat: 45.0107063,
    lng: 8.6459065,
  },
  {
    name: "Giardini Pubblici Aldo Moro",
    category: "outdoors",
    type: "Parque",
    address: "Via del Bocciofilo",
    city: "Valenza",
    notes: "El parque de juegos más grande",
    lat: 45.0116727,
    lng: 8.6344707,
  },
  {
    name: "Giardino Camurati",
    category: "outdoors",
    type: "Parque",
    address: "Valenza (centro, Via Mazzini)",
    city: "Valenza",
    notes: "Pequeño espacio verde céntrico",
    lat: 45.0144749,
    lng: 8.6390701,
  },
  {
    name: "Lago Golden Carp Fishing",
    category: "outdoors",
    type: "Pesca deportiva",
    address: "SP55 Casale-Valenza, Pomaro Monferrato",
    city: "Pomaro Monferrato",
    phone: "+39 393 395 9487",
    notes: "Pesca en lago (o directa en el Po)",
    lat: 45.0775329,
    lng: 8.5691898,
  },
  {
    name: "Terme di Monte Valenza",
    category: "wellness",
    type: "Termas/Piscina",
    address: "Via Fontana 13, Monte",
    city: "Monte Valenza",
    phone: "+39 0131 945253",
    notes: "Termas + pileta verano + mini-zoo",
    lat: 45.0416814,
    lng: 8.6085358,
  },
  {
    name: "Piscine di Bassignana",
    category: "wellness",
    type: "Piscina",
    address: "Strada del Porto",
    city: "Bassignana",
    phone: "+39 366 497 7116",
    notes: "Pileta de verano",
    lat: 44.995764,
    lng: 8.7307664,
  },
  {
    name: "Yoga Sushumna",
    category: "wellness",
    type: "Yoga",
    address: "Via Sebastian Bach",
    city: "Valenza",
    phone: "+39 335 609 7911",
    notes: "Clases, también principiantes",
    lat: 45.0135046,
    lng: 8.6354038,
  },
  {
    name: "Studio Pilates 88",
    category: "wellness",
    type: "Pilates",
    address: "Via Carlo Tortrino 13",
    city: "Valenza",
    phone: "+39 331 813 9206",
    notes: "Postural/personal, no es gym de fierros",
    lat: 45.00831,
    lng: 8.640054,
  },
  {
    name: "Centro Olistico Spina Simona",
    category: "wellness",
    type: "Holístico/Masaje",
    address: "Via Gioacchino Rossini 3",
    city: "Valenza",
    phone: "+39 379 110 0488",
    notes: "Disciplinas olísticas",
    lat: 45.0144978,
    lng: 8.6343859,
  },
  {
    name: "Pro Loco Valenza",
    category: "associations",
    type: "Asociación/Eventos",
    address: "Via San Giovanni 21",
    city: "Valenza",
    phone: "+39 0131 950131",
    notes: "Mercados, cenas, eventos; se puede colaborar",
    lat: 45.0140033,
    lng: 8.6419273,
  },
  {
    name: "AVIS Valenza",
    category: "associations",
    type: "Donación de sangre",
    address: "Viale Alessandro Manzoni 6",
    city: "Valenza",
    phone: "+39 0131 924060",
    notes: "Sección local activa",
    lat: 45.0157874,
    lng: 8.6389346,
  },
  {
    name: "Primolancio - Plane Club Alexandria",
    category: "niche",
    type: "Paracaidismo",
    address: "Viale Milite Ignoto 19, Alessandria",
    city: "Alessandria",
    phone: "+39 328 147 7412",
    notes: "Salto tándem/freefly; aviones/planeadores",
    lat: 44.9250073,
    lng: 8.6231897,
  },
  {
    name: "Aviosuperficie Centro ULM",
    category: "niche",
    type: "Vuelo ultraligero",
    address: "SP84, Alluvioni Piovera",
    city: "Alluvioni Piovera",
    notes: "Volar en ULM sobre la llanura del Po",
    lat: 44.9361154,
    lng: 8.7487264,
  },
  {
    name: "Pista Alessandria",
    category: "niche",
    type: "Karting/Motard",
    address: "Via San Bartolomeo, Alessandria",
    city: "Alessandria",
    phone: "+39 393 923 6005",
    notes: "Pista moto/kart + simulador",
    lat: 44.938877,
    lng: 8.6274649,
  },
  {
    name: "Fuorigiri Minibike Academy",
    category: "niche",
    type: "Minimoto/Kart",
    address: "Valle San Bartolomeo, Alessandria",
    city: "Alessandria",
    phone: "+39 393 923 6005",
    notes: "Mini-motard, apto chicos",
    lat: 44.9393428,
    lng: 8.6277444,
  },
  {
    name: "Pista Kart Bosco",
    category: "niche",
    type: "Karting",
    address: "Via Vecchia Reale 4",
    city: "Ss 35 bis dei Giovi",
    phone: "+39 327 202 2213",
    notes: "Kart indoor/outdoor + simulador (~40 km)",
    lat: 44.841223,
    lng: 8.7290264,
  },
  {
    name: "a.s.d. Wild West",
    category: "niche",
    type: "Equitación western",
    address: "Strada Ariara",
    city: "Valenza",
    phone: "+39 333 990 6263",
    notes: "Monta western y cabalgatas, en Valenza",
    lat: 45.007911,
    lng: 8.6672585,
  },
  {
    name: "Diletta Monferrato a Cavallo",
    category: "niche",
    type: "Cabalgatas",
    address: "SP494 km 80.5",
    city: "Valenza",
    notes: "Paseos a caballo por las colinas de Valenza",
    lat: 44.9875584,
    lng: 8.6390622,
  },
  {
    name: "Centro Ippico La Fonte",
    category: "niche",
    type: "Equitación",
    address: "Regione Bettola 19, Casale Monferrato",
    city: "Casale Monferrato",
    phone: "+39 339 100 9125",
    notes: "Monta inglesa y western",
    lat: 45.058787,
    lng: 8.4596805,
  },
  {
    name: "Società Canottieri Casale",
    category: "niche",
    type: "Remo",
    address: "Viale Lungo Po Gramsci 14, Casale",
    city: "Casale Monferrato",
    phone: "+39 0142 453071",
    notes: "Remo en el Po (+tenis/pádel/pileta)",
    lat: 45.1369919,
    lng: 8.4442956,
  },
  {
    name: "Amici del Po",
    category: "niche",
    type: "Barcas típicas del Po",
    address: "Viale Morozzo S. Michele 3, Casale",
    city: "Casale Monferrato",
    phone: "+39 349 839 3726",
    notes: "Paseos en batane + orilla",
    lat: 45.1413907,
    lng: 8.4500482,
  },
  {
    name: "A.S.D. Arcieri Città della Paglia",
    category: "niche",
    type: "Tiro con arco",
    address: "Via Salvo D'Acquisto 16, Alessandria",
    city: "Alessandria",
    notes: "Campo con tradición (5.0)",
    lat: 44.9103262,
    lng: 8.6340028,
  },
  {
    name: "DLF Tiro con l'Arco",
    category: "niche",
    type: "Tiro con arco",
    address: "Via Carlo Alberto 1, Alessandria",
    city: "Alessandria",
    phone: "+39 0131 252079",
    notes: "Campo de tiro con arco",
    lat: 44.9046485,
    lng: 8.6079527,
  },
  {
    name: "Parco del Cielo (Astrofili Galileo)",
    category: "niche",
    type: "Astronomía",
    address: "Pecetto di Valenza",
    city: "Pecetto di Valenza",
    notes: "Sistema solar a escala 200 m; visitas y serate osservative",
    lat: 44.985702,
    lng: 8.668434,
  },
  {
    name: "ONAV Sezione Alessandria",
    category: "niche",
    type: "Cata de vino (curso)",
    address: "Alessandria",
    city: "Alessandria",
    phone: "alessandria@onav.it",
    notes: "Curso itinerante, algunas noches en cantine",
    lat: 44.912985,
    lng: 8.615456,
  },
  {
    name: "Festa di San Massimo",
    category: "event",
    type: "Fiesta patronal",
    address: "Duomo, Piazza 31 Martiri 3",
    city: "Valenza",
    notes: "Última dom. de enero; misa, benedizione ceri, rievocazione en costume",
    lat: 45.0146598,
    lng: 8.6462616,
  },
  {
    name: "Festa patronale di San Giacomo",
    category: "event",
    type: "Fiesta patronal",
    address: "Piazza XXXI Martiri",
    city: "Valenza",
    notes: "Fines de julio, desde 21:30",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Corsa non competitiva 'La Gelsi'",
    category: "event",
    type: "Carrera popular",
    address: "Valenza (centro)",
    city: "Valenza",
    notes: "Mayo; corrida/caminata no competitiva",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Carnevale di Valenza",
    category: "event",
    type: "Carnaval",
    address: "Valenza (centro)",
    city: "Valenza",
    notes: "Febrero; desfile de carros alegóricos",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Concorso Sant'Eligio",
    category: "event",
    type: "Concurso joyería",
    address: "Valenza",
    city: "Valenza",
    notes: "Mayo; concurso nacional del joyel",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Valenza Jewelry Week",
    category: "event",
    type: "Feria/Exposición joyería",
    address: "Centro storico (Palazzo Valentino, San Rocco, Villa Scalcabarozzi)",
    city: "Valenza",
    notes: "Mayo; exposiciones de joyería y arte",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Valenza Gem Forum",
    category: "event",
    type: "Foro gemas/joyería",
    address: "Valenza",
    city: "Valenza",
    notes: "Octubre; foro del sector",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Mostra Orafa / feria del joyel",
    category: "event",
    type: "Feria orfebre",
    address: "Palazzo Mostre",
    city: "Valenza",
    notes: "Primavera y otoño (tradicional)",
    lat: 45.014025,
    lng: 8.645821,
  },
  {
    name: "Valenza è in Fiore",
    category: "event",
    type: "Feria de flores",
    address: "Viale Oliva",
    city: "Valenza",
    notes: "Abril; mercado de plantas/flores + gastronomía",
    lat: 45.0107063,
    lng: 8.6459065,
  },
  {
    name: "Rievocazione Battaglia di Marengo",
    category: "event",
    type: "Recreación histórica",
    address: "Villa Delavo (Marengo Museum), Via Delavo, Spinetta Marengo",
    city: "Alessandria",
    phone: "serviziomusei@asmcostruireinsieme.it",
    notes: "Mediados de junio; +100 recreadores, caballería, cañones; reservar",
    lat: 44.9068,
    lng: 8.6877,
  },
  {
    name: "Moto Marengo (Moto Club Marengo)",
    category: "event",
    type: "Concentración de motos",
    address: "Marengo, Spinetta Marengo",
    city: "Alessandria",
    notes: "Junio; parata motociclística ligada a Marengo",
    lat: 44.9068,
    lng: 8.6877,
  },
  {
    name: "Riso & Rose in Monferrato",
    category: "event",
    type: "Circuito de eventos",
    address: "Varias localidades (Monferrato Casalese / piana del Po / Lomellina)",
    city: "Casale Monferrato",
    notes: "Tres findes de mayo; flores, arte, food, castillos abiertos",
    lat: 45.136266,
    lng: 8.449813,
  },
]
